title: Conceito Vida
tagline: Cirurgia Pl√°stica & Longevidade
url: "http://localhost:4000"
baseurl: ""

exclude:
  - css/app.css.map
  - Gemfile
  - Gemfile.lock
  - install
  - LICENSE
  - README.md

sass:
  sass_dir: css
  style: compressed

google-maps-api: my-dev-googlep-maps-javascript-api

contact:
  address1: Av. Doutor Hermas Braga, 396
  address2: Nova Campinas - Campinas - SP
  phone: +551932540492
  phone_for_humans: (19) 3254.0492
  email: contato@conceitovida.com.br
